export const Keyboard = Object.freeze({
    PriorVertex: 'Shift+Tab',
    NextVertex: 'Tab',
    MovePointLeft: 'ArrowLeft',
    MovePointRight: 'ArrowRight',
    MovePointUp: 'ArrowUp',
    MovePointDown: 'ArrowDown',
    MovePointUpLeft: ['Control+ArrowLeft+ArrowUp', 'ArrowLeft+ArrowUp'],
    MovePointUpRight: ['Control+ArrowRight+ArrowUp', 'ArrowRight+ArrowUp'],
    MovePointDownLeft: ['Control+ArrowLeft+ArrowDown', 'ArrowLeft+ArrowDown'],
    MovePointDownRight: [
        'Control+ArrowRight+ArrowDown',
        'ArrowRight+ArrowDown',
    ],
    CenterAt: 'c',
    Delete: ['Delete', 'Backspace', 'Shift+Left+mousedown'],
    ZoomIn: ['+', '=', 'Shift++', 'Spread'],
    ZoomOut: ['-', 'Shift+_', 'Pinch'],
    PanLeft: ['DragDragRight', 'Shift+ArrowLeft'],
    PanRight: ['DragDragLeft', 'Shift+ArrowRight'],
    PanUp: ['DragDragDown', 'Shift+ArrowUp'],
    PanDown: ['DragDragUp', 'Shift+ArrowDown'],
    PanFrom: ['mousemove'],
    PanTo: ['Shift+mousemove'],
    Reset: 'Shift+Escape',
    StartDragging: ['Left+mousedown', ' +Left+mousedown', 'touchmove'],
    Dragging: ['Left+mousemove', ' +Left+mousemove', 'touchmove'],
    EndDragging: ['Left+mouseup', ' +Left+mouseup', 'touchend'],
    PlacingVertex: ['mousemove'],
    PlaceVertex: ['Left+mousedown'],
    ClearInterior: 'Shift+X',
    ClearExterior: 'Control+Shift+X',
    Smooth: 'q',
    ClosePolygon: ['Right+mousedown', 'touchend'],
    DeleteAndClosePolygon: ['Escape'],
    InsertPointAtCursorPosition: [' ', ' +Left+mousemove'],
    Hover: ['Shift+mousemove', 'mousemove', 'touchmove'],
    PlaceFirstVertex: ['Left+mousedown', 'touchstart'],
    Drawing: ['Left+mousedown', 'touchmove', 'touchstart'],
});
