export const Keyboard = Object.freeze({
    PriorVertex: 'Shift+Tab',
    NextVertex: 'Tab',
    MovePointLeft: 'ArrowLeft',
    MovePointRight: 'ArrowRight',
    MovePointUp: 'ArrowUp',
    MovePointDown: 'ArrowDown',
    MovePointUpLeft: ['Control+ArrowLeft+ArrowUp', 'ArrowLeft+ArrowUp'],
    MovePointUpRight: ['Control+ArrowRight+ArrowUp', 'ArrowRight+ArrowUp'],
    MovePointDownLeft: ['Control+ArrowLeft+ArrowDown', 'ArrowLeft+ArrowDown'],
    MovePointDownRight: [
        'Control+ArrowRight+ArrowDown',
        'ArrowRight+ArrowDown',
    ],
    ClonePoint: [' '],
    CenterAt: 'c',
    Delete: ['Delete','Backspace'],
    ZoomIn: ['+', '=', 'Shift++', 'Spread'],
    ZoomOut: ['-', 'Shift+_', 'Pinch'],
    PanLeft: ['DragDragRight', 'Shift+ArrowLeft'],
    PanRight: ['DragDragLeft', 'Shift+ArrowRight'],
    PanUp: ['DragDragDown', 'Shift+ArrowUp'],
    PanDown: ['DragDragUp', 'Shift+ArrowDown'],
    PanFrom: ['mousemove'],
    PanTo: ['Shift+mousemove'],
    Reset: 'Shift+Escape',
    ClearInterior: 'Shift+X',
    ClearExterior: 'Control+Shift+X',
    Smooth: 'q',
    ClosePolygon: ['Right+mousedown', 'touchend'],
    DeleteAndClosePolygon: ['Escape'],
    InsertPointAtCursorPosition: [' '],
});
